# Generated by Django 5.1.3 on 2024-12-15 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255, null=True)),
                ('year', models.IntegerField()),
                ('brand', models.CharField(max_length=45)),
                ('model', models.CharField(max_length=45)),
                ('price', models.FloatField()),
                ('tags', models.CharField(max_length=100, null=True)),
                ('url', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MailVerify',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=4)),
                ('email', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=45, unique=True)),
                ('state', models.IntegerField(default=0)),
                ('password', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=45, null=True)),
                ('mid', models.TextField(null=True)),
                ('token', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mask',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=255, null=True)),
                ('likes', models.TextField(null=True)),
                ('dislikes', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
