# Generated by Django 5.1.4 on 2024-12-27 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reminder_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='reminder_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='reminder_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='reminder_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='reminder_5',
            field=models.IntegerField(default=0),
        ),
    ]
